(() => {'use strict';
const $=id=>document.getElementById(id),L=window.NayaLife,KEY='naya-atelier-life-v1';
let state=L.fresh(),view='atelier',atlas=null,assetReady=false,selected=null,roomDrag=null,history=[],frame='pink',voice=false,noticeTimer,heartTimer;
try{const raw=localStorage.getItem(KEY);if(raw)state=L.restore(JSON.parse(raw));}catch(e){try{const raw=localStorage.getItem(KEY);if(raw)localStorage.setItem(KEY+'-recovery',raw);}catch(ignore){}}
// Each generated cutout occupies one atlas cell. Source rectangles are calibrated after visual inspection.
const sprites={bed:[0,0,500,535],rug:[500,230,435,305],lamp:[935,0,270,535],plant:[1205,0,331,535],happy:[0,535,365,489],sleep:[390,535,407,489],play:[797,535,406,489],eat:[1203,535,333,489]};
const trimmed={};
function sprite(canvas,kind){if(!assetReady)return;const [x,y,w,h]=trimmed[kind]||sprites[kind],c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);const scale=Math.min(canvas.width/w,canvas.height/h);c.drawImage(atlas,x,y,w,h,(canvas.width-w*scale)/2,(canvas.height-h*scale)/2,w*scale,h*scale);}
function speak(text){if(!voice||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const line=new SpeechSynthesisUtterance(text);line.lang='de-DE';line.rate=.88;const de=speechSynthesis.getVoices().find(v=>v.lang.startsWith('de'));if(de)line.voice=de;speechSynthesis.speak(line);}catch(ignore){}}
function notice(symbol,text){$('toast').textContent=symbol;$('toast').setAttribute('aria-label',text);$('toast').classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('toast').classList.remove('show'),1800);speak(text);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch(e){notice('💾 ❗','Dein Gerät konnte gerade nicht speichern.');return false;}}
function remember(){history.push(state);if(history.length>16)history.shift();}
function commit(next,undo=true){if(next===state)return;if(undo)remember();state=next;save();render();}
function setView(next){if(!assetReady){notice('🌸 …','Die neuen Bilder laden noch.');return;}if(!['atelier','room','adventures','album'].includes(next))return;view=next;document.querySelector('.atelier').dataset.view=next;document.querySelector('.playroom').hidden=next!=='atelier';$('life-content').hidden=next==='atelier';$('atelier-photo').hidden=next!=='atelier';$('atelier-pet').hidden=next!=='atelier';document.querySelectorAll('.life-view').forEach(el=>el.hidden=el.id!==next+'-view');document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('chosen',b.dataset.view===next);b.setAttribute('aria-pressed',b.dataset.view===next);});selected=null;render();}
function dollInRoom(){const doll=$('doll');try{$('room-doll').src=doll.toDataURL('image/png');}catch(ignore){}}
function renderPets(){document.querySelectorAll('.pet-canvas').forEach(c=>sprite(c,state.petMode));document.querySelectorAll('.pet-name').forEach(el=>el.textContent=state.petName);for(const id of ['atelier-pet','room-pet']){$(id).setAttribute('aria-label',state.petName+' streicheln');$(id).classList.toggle('sleepy',state.petMode==='sleep');} }
function renderRoom(){const stage=$('room-stage');stage.dataset.wall=state.wall;stage.classList.toggle('night',!state.light);$('room-light').textContent=state.light?'💡':'🌑';$('room-light').setAttribute('aria-label',state.light?'Licht ausschalten':'Licht einschalten');$('bed-dream').hidden=state.light||!state.objects.some(o=>o.kind==='bed');$('room-sleep').setAttribute('aria-label',state.light?'Schlafen gehen':'Aufwachen');$('room-sleep').textContent=state.light?'🌙':'☀️';$('room-undo').disabled=!history.length;$('room-delete').hidden=!selected;
 const container=$('room-objects');container.replaceChildren();for(const item of state.objects){const b=document.createElement('button');b.className='furniture'+(selected===item.kind?' selected':'');b.dataset.kind=item.kind;b.setAttribute('aria-label',({bed:'Bett',rug:'Teppich',lamp:'Lampe',plant:'Pflanze'})[item.kind]+' verschieben');b.style.left=item.x*100+'%';b.style.top=item.y*100+'%';b.style.zIndex=item.kind==='rug'?0:Math.round(item.y*10);const c=document.createElement('canvas');const rect=trimmed[item.kind]||sprites[item.kind];c.width=400;c.height=Math.round(400*rect[3]/rect[2]);sprite(c,item.kind);b.append(c);bindDrag(b,item.kind,false);b.onclick=e=>{if(e.detail===0){selected=item.kind;renderRoom();}};container.append(b);}document.querySelectorAll('[data-wall]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.wall===state.wall));dollInRoom();}
function renderAlbum(){$('album-undo').disabled=!history.length;const grid=$('album-grid');grid.replaceChildren();state.album.forEach((photo,index)=>{const card=document.createElement('article');card.className='album-card';card.dataset.frame=photo.frame;const img=new Image();img.src=photo.image;img.alt='Dein Moment '+(index+1);const sticker=document.createElement('span');sticker.className='sticker';sticker.textContent=photo.frame==='mint'?'🌿 🐈 💚':photo.frame==='lavender'?'🪻 ✨ 💜':'🌸 💗 ✨';const remove=document.createElement('button');remove.textContent='×';remove.setAttribute('aria-label','Foto '+(index+1)+' aus dem Album entfernen');remove.onclick=()=>commit({...state,album:state.album.filter((_,i)=>i!==index)});card.append(img,sticker,remove);grid.append(card);});$('album-empty').hidden=!!state.album.length;document.querySelectorAll('[data-frame]').forEach(b=>b.classList.toggle('active',b.dataset.frame===frame));}
const questNames={picnic:'Unser Picknick',party:'Eine kleine Party',sleep:'Gute Nacht'};
const questWords={outfit:'Such dir schöne Kleider aus.',food:'Gib deiner Freundin eine Erdbeere.',play:'Spiel mit deinem Kätzchen.',bracelet:'Such ein Armband aus.',lamp:'Stell eine Lampe ins Zimmer.',bed:'Stell ein Bett ins Zimmer.',cuddle:'Streichle dein Kätzchen.',night:'Mach es gemütlich und geh schlafen.'};
function guide(){const active=state.active;$('quest-guide').hidden=!active;document.querySelectorAll('[data-quest]').forEach(b=>b.classList.toggle('finished',state.completed.includes(b.dataset.quest)));if(!active)return;const steps=L.quests[active.id];$('quest-steps').replaceChildren();steps.forEach((step,i)=>{const el=document.createElement('span');el.textContent=i<active.step?'✓':step.icon;el.className=i<active.step?'done':i===active.step?'current':'';el.setAttribute('aria-label',i<active.step?'Geschafft':questWords[step.event]);$('quest-steps').append(el);});$('quest-go').textContent=steps[active.step].icon+' Los geht’s ➜';$('quest-go').setAttribute('aria-label',questWords[steps[active.step].event]);}
function render(){renderPets();guide();if(view==='room')renderRoom();if(view==='album')renderAlbum();}
function event(kind){const active=state.active,next=L.event(state,kind);if(next===state)return;commit(next,false);if(!next.active){$('finish-title').textContent=questNames[active.id]+' · geschafft!';$('quest-finish').showModal();notice('🌈 ✨ 💗','Das war schön! Dein Abenteuer ist geschafft.');}else{const step=L.quests[next.active.id][next.active.step];notice('✓ '+step.icon,questWords[step.event]);}}
function goStep(){if(!state.active)return;const step=L.quests[state.active.id][state.active.step];speak(questWords[step.event]);if(step.target==='room'||step.target==='pet'){setView('room');if(step.target==='pet'){$('room-pet').classList.add('playful');setTimeout(()=>$('room-pet').classList.remove('playful'),700);}}else{setView('atelier');document.querySelector('[data-category="'+step.target+'"]').click();}}
function care(mode){if(!assetReady)return;commit(L.pet(state,mode),false);for(const id of ['atelier-pet','room-pet']){$(id).classList.remove('playful');void $(id).offsetWidth;if(mode!=='sleep')$(id).classList.add('playful');}setTimeout(()=>document.querySelectorAll('.pet-button').forEach(b=>b.classList.remove('playful')),750);$('pet-hearts').textContent=mode==='eat'?'🥣 😋':mode==='play'?'🧶 ✨':'💗 💗';clearTimeout(heartTimer);heartTimer=setTimeout(()=>$('pet-hearts').textContent='',1500);notice(mode==='eat'?'🥣 😋':mode==='play'?'🧶 ✨':'💗 🐈',mode==='eat'?'Mmm, lecker!':mode==='play'?'Komm, wir spielen!':'Das mag ich!');event(mode==='happy'?'cuddle':mode==='play'?'play':'feed');}
let ghost=document.createElement('canvas');ghost.width=320;ghost.height=260;ghost.className='life-ghost';ghost.hidden=true;document.body.append(ghost);
function bindDrag(button,kind,palette){button.addEventListener('pointerdown',e=>{if(e.button!==0||!assetReady)return;e.preventDefault();button.setPointerCapture(e.pointerId);roomDrag={id:e.pointerId,kind,palette,x:e.clientX,y:e.clientY,moved:false};});button.addEventListener('click',e=>{if(e.detail===0&&palette){commit(L.place(state,kind,.3+Math.random()*.38,.82));event(kind);}});}
function dropPoint(x,y){const r=$('room-stage').getBoundingClientRect();return {inside:x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom,x:(x-r.left)/r.width,y:(y-r.top)/r.height};}
function endDrag(){roomDrag=null;ghost.hidden=true;$('room-stage').classList.remove('drop-ready');}
document.addEventListener('pointermove',e=>{if(!roomDrag||roomDrag.id!==e.pointerId)return;const d=roomDrag;if(!d.moved&&Math.hypot(e.clientX-d.x,e.clientY-d.y)>7){d.moved=true;sprite(ghost,d.kind);ghost.hidden=false;}if(d.moved){ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px';$('room-stage').classList.toggle('drop-ready',dropPoint(e.clientX,e.clientY).inside);}});
document.addEventListener('pointerup',e=>{if(!roomDrag||roomDrag.id!==e.pointerId)return;const d=roomDrag,p=dropPoint(e.clientX,e.clientY);endDrag();if(d.moved){if(p.inside){selected=d.kind;commit(L.place(state,d.kind,p.x,p.y));event(d.kind);}}else if(d.palette){selected=d.kind;const old=state.objects.find(o=>o.kind===d.kind);commit(L.place(state,d.kind,old?.x??.35,old?.y??.8));event(d.kind);}else{selected=d.kind;renderRoom();}});
document.addEventListener('pointercancel',endDrag);window.addEventListener('blur',endDrag);
function takePhoto(){if(!assetReady)return;const c=document.createElement('canvas');c.width=320;c.height=430;const ctx=c.getContext('2d'),bg=new Image();bg.onload=()=>{ctx.drawImage(bg,0,0,bg.width,bg.height,0,0,320,430);if(view==='room'){const ordered=[...state.objects].sort((a,b)=>a.kind==='rug'?-1:b.kind==='rug'?1:a.y-b.y);for(const item of ordered){const rect=trimmed[item.kind]||sprites[item.kind],w=item.kind==='bed'?145:item.kind==='rug'?250:75,h=w*rect[3]/rect[2];ctx.drawImage(atlas,...rect,item.x*320-w/2,item.y*400-h,w,h);}}ctx.drawImage($('doll'),68,10,244,382);const rect=trimmed[state.petMode]||sprites[state.petMode],w=96,h=w*rect[3]/rect[2];ctx.drawImage(atlas,...rect,10,418-h,w,h);ctx.fillStyle='#fff0d9eb';ctx.fillRect(0,0,320,35);ctx.fillStyle='#805b91';ctx.font='bold 17px system-ui';ctx.textAlign='center';ctx.fillText('Naya & '+state.petName,160,24);const image=c.toDataURL('image/jpeg',.78);if(state.album.length>=8){notice('📸 8 💗','Dein Album ist voll. Du kannst ein Foto entfernen und zurückholen.');return;}commit({...state,album:[...state.album,{image,frame,time:Date.now()}].slice(-8)});notice('📸 💗','Dein Foto ist im Album.');};bg.onerror=()=>notice('📸 ❗','Das Foto konnte gerade nicht erstellt werden.');bg.src='./atelier-assets/room.webp';}
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>setView(b.dataset.view);
for(const b of document.querySelectorAll('[data-furniture]'))bindDrag(b,b.dataset.furniture,true);
for(const b of document.querySelectorAll('[data-wall]'))b.onclick=()=>commit({...state,wall:b.dataset.wall});
for(const b of document.querySelectorAll('[data-pet]'))b.onclick=()=>care(b.dataset.pet);
for(const b of document.querySelectorAll('[data-photo]'))b.onclick=takePhoto;
for(const b of document.querySelectorAll('[data-frame]'))b.onclick=()=>{frame=b.dataset.frame;if(state.album.length){const album=state.album.map((a,i)=>i===state.album.length-1?{...a,frame}:a);commit({...state,album});}else renderAlbum();};
for(const b of document.querySelectorAll('[data-quest]'))b.onclick=()=>{commit(L.start(state,b.dataset.quest),false);goStep();};
$('quest-go').onclick=goStep;$('quest-stop').onclick=()=>commit({...state,active:null},false);
$('room-delete').onclick=()=>{if(selected){const kind=selected;selected=null;commit(L.remove(state,kind));notice('🗑️ ✓','Du kannst es mit dem Pfeil zurückholen.');}};
$('album-undo').onclick=$('room-undo').onclick=()=>{if(history.length){state=history.pop();selected=null;save();render();}};
$('room-light').onclick=()=>{commit({...state,light:!state.light});if(!state.light)event('night');};
$('room-sleep').onclick=()=>{if(state.light&&!state.objects.some(o=>o.kind==='bed')){notice('🛏️ ➜','Stell zuerst ein Bett ins Zimmer.');return;}const night=state.light;commit({...state,light:!night,petMode:night?'sleep':'happy'});if(night){event('night');speak('Gute Nacht, Naya.');}else speak('Guten Morgen!');};
$('atelier-pet').onclick=$('room-pet').onclick=()=>care('happy');
$('pet-name-button').onclick=()=>{$('pet-name-input').value=state.petName;$('pet-dialog').showModal();};
$('pet-dialog').querySelector('form').onsubmit=e=>{if(e.submitter?.value==='save'){const name=$('pet-name-input').value.replace(/[<>\u0000-\u001f]/g,'').trim().slice(0,16);commit({...state,petName:name||'Mimi'},false);notice('🐈 💗',state.petName+' ist dein Kätzchen.');}};
$('finish-photo').onclick=()=>{$('quest-finish').close();takePhoto();};$('finish-close').onclick=()=>$('quest-finish').close();
$('voice').onclick=()=>{voice=!voice;$('voice').textContent=voice?'🔊':'🔈';$('voice').setAttribute('aria-pressed',voice);$('voice').setAttribute('aria-label',voice?'Stimme ausschalten':'Stimme einschalten');if(voice)speak('Hallo Naya! Schön, dass du da bist.');};if(!('speechSynthesis'in window))$('voice').hidden=true;
document.addEventListener('atelier:choice',e=>{dollInRoom();event(e.detail.kind);if(e.detail.kind==='food')speak('Mmm, lecker!');else if(e.detail.kind==='drink')speak('Danke!');else speak('Das sieht schön aus!');});
document.addEventListener('atelier:ready',dollInRoom);
window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden){endDrag();save();if('speechSynthesis'in window)speechSynthesis.cancel();}});
atlas=new Image();atlas.onload=()=>{assetReady=true;const temp=document.createElement('canvas');temp.width=atlas.width;temp.height=atlas.height;const c=temp.getContext('2d',{willReadFrequently:true});c.drawImage(atlas,0,0);const pixels=c.getImageData(0,0,atlas.width,atlas.height).data;for(const [kind,[x,y,w,h]]of Object.entries(sprites)){let left=x+w,right=x,top=y+h,bottom=y;for(let py=y;py<y+h;py++)for(let px=x;px<x+w;px++)if(pixels[(py*atlas.width+px)*4+3]>110){left=Math.min(left,px);right=Math.max(right,px);top=Math.min(top,py);bottom=Math.max(bottom,py);}trimmed[kind]=right>left?[left,top,right-left+1,bottom-top+1]:sprites[kind];}document.querySelectorAll('[data-furniture]').forEach(b=>sprite(b.querySelector('canvas'),b.dataset.furniture));render();dollInRoom();save();};atlas.onerror=()=>{notice('🏡 ↻','Die neuen Bilder konnten nicht laden. Öffne das Spiel noch einmal.');};atlas.src='./atelier-assets/life.webp';
setInterval(()=>{if(document.hidden||state.petMode!=='play')return;const p=view==='room'?$('room-pet'):$('atelier-pet');p.classList.add('playful');setTimeout(()=>p.classList.remove('playful'),750);},9000);
})();
