(() => {
'use strict';
const $=id=>document.getElementById(id),M=window.NayaAtelier,KEY='naya-atelier-v1',ctx=$('doll').getContext('2d');
let state=M.fresh(),history=[],category='clothes',drag=null,gesture=null,ready=false,toastTimer,reactionTimer,careTimer,music=false,audioCtx,musicTimer,noteIndex=0,changed=0;
try{const text=localStorage.getItem(KEY);if(text)state=M.restore(JSON.parse(text));}catch(e){try{const raw=localStorage.getItem(KEY);if(raw)localStorage.setItem(KEY+'-recovery',raw);}catch(ignore){}}
const DB={
 clothes:[{kind:'outfit',value:0,name:'Blumenjacke',art:'cardigan',tint:true},{kind:'outfit',value:1,name:'Blumenkleid',art:'dress'},{kind:'outfit',value:2,name:'Latzhose',art:'overall'},{kind:'outfit',value:3,name:'Korallenjacke',art:'cardigan'},{kind:'shoes',value:1,name:'Blümchenschuhe',foot:1},{kind:'bracelet',value:'flowers',name:'Blumenarmband',art:'bracelet'}],
 hair:[{kind:'hair',value:'brown',name:'Kastanie',hair:true},{kind:'hair',value:'honey',name:'Honig',hair:true},{kind:'hair',value:'auburn',name:'Kupfer',hair:true},{kind:'hair',value:'dark',name:'Dunkelbraun',hair:true}],
 shoes:[{kind:'shoes',value:0,name:'Lila Sneakers',foot:0},{kind:'shoes',value:1,name:'Blümchenschuhe',foot:1},{kind:'shoes',value:2,name:'Mint Sneakers',foot:2},{kind:'shoes',value:3,name:'Blumenballerinas',foot:3},{kind:'socks',value:'mint',name:'Mint Socken',art:'socks'},{kind:'socks',value:'pink',name:'Rosa Socken',art:'socks',tint:true}],
 jewelry:[{kind:'bracelet',value:'flowers',name:'Blumenarmband',art:'bracelet'},{kind:'bracelet',value:'rainbow',name:'Regenbogen',art:'bracelet'},{kind:'bracelet',value:'pearls',name:'Perlen',emoji:'🤍'},{kind:'bracelet',value:'stars',name:'Sternenarmband',emoji:'⭐'}],
 makeup:[{kind:'lip',value:'natural',name:'Natürlich',emoji:'🌼'},{kind:'lip',value:'rose',name:'Rosa',emoji:'💄',swatch:'#d88e9f'},{kind:'lip',value:'peach',name:'Pfirsich',emoji:'💄',swatch:'#dfaa85'},{kind:'lip',value:'berry',name:'Beere',emoji:'💄',swatch:'#b77697'}],
 food:[{kind:'food',value:'strawberry',name:'Erdbeere',art:'strawberry'},{kind:'food',value:'apple',name:'Apfel',emoji:'🍎'},{kind:'food',value:'banana',name:'Banane',emoji:'🍌'},{kind:'drink',value:'water',name:'Wasser',art:'water'},{kind:'drink',value:'juice',name:'Saft',emoji:'🧃'},{kind:'drink',value:'milk',name:'Milch',emoji:'🥛'}]
};
const bounds=[{x:249,y:20,w:269,h:599},{x:775,y:20,w:267,h:599},{x:249,y:638,w:270,h:598},{x:771,y:638,w:272,h:599}];
const feetBounds=[{x:141,y:257,w:416,h:404},{x:772,y:257,w:410,h:406},{x:140,y:799,w:421,h:409},{x:772,y:799,w:409,h:404}];
const crop={dress:[964,157,141,196],overall:[1161,155,190,197],cardigan:[929,388,173,189],bracelet:[1173,611,148,151],socks:[950,610,135,163],strawberry:[43,239,119,104],water:[44,449,107,113]};
const images={};function loadImage(url){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url;});}
const scratch=document.createElement('canvas');scratch.width=640;scratch.height=1000;const sx=scratch.getContext('2d',{willReadFrequently:true});
const mask=document.createElement('canvas');mask.width=640;mask.height=1000;const mx=mask.getContext('2d');mx.fillStyle='white';mx.beginPath();mx.moveTo(145,14);mx.bezierCurveTo(235,-12,440,0,500,100);mx.bezierCurveTo(565,170,555,450,480,602);mx.lineTo(425,557);mx.lineTo(210,575);mx.lineTo(103,533);mx.bezierCurveTo(70,355,97,91,145,14);mx.fill();mx.globalCompositeOperation='destination-out';mx.beginPath();mx.ellipse(330,204,93,115,-.18,0,Math.PI*2);mx.fill();mx.fillRect(218,292,226,326);
const hairMask=mx.getImageData(0,0,640,1000).data;
function base(c,outfit){const b=bounds[outfit],scale=940/b.h;c.drawImage(images.dolls,b.x,b.y,b.w,b.h,320-b.w*scale/2,20,b.w*scale,940);}
function recolorHair(c,value,outfit=state.outfit){if(value==='brown')return;sx.clearRect(0,0,640,1000);base(sx,outfit);const pixels=sx.getImageData(0,0,640,1000),p=pixels.data;const tones={honey:[184,136,76],auburn:[142,66,45],dark:[59,42,35]},tone=tones[value];for(let i=0;i<p.length;i+=4){const r=p[i],g=p[i+1],b=p[i+2];if(!hairMask[i+3]||p[i+3]<8||r<g*1.1||g<b*1.04){p[i+3]=0;continue;}const light=(r*.3+g*.59+b*.11)/105;p[i]=Math.min(255,tone[0]*light);p[i+1]=Math.min(255,tone[1]*light);p[i+2]=Math.min(255,tone[2]*light);p[i+3]=Math.round(p[i+3]*hairMask[i+3]/255*.86);}sx.putImageData(pixels,0,0);c.drawImage(scratch,0,0);}
function feet(c){const b=feetBounds[state.shoes];c.drawImage(images.feet,b.x,b.y,b.w,b.h,110,620,350,340);if(state.socks==='mint')return;
 const segment=document.createElement('canvas');segment.width=640;segment.height=1000;const sc=segment.getContext('2d',{willReadFrequently:true});sc.drawImage(images.feet,b.x,b.y,b.w,b.h,110,620,350,340);const pixels=sc.getImageData(0,0,640,1000),p=pixels.data;
 // Change only green sock yarn, preserving skin, white stripes, and footwear.
 for(let y=720;y<865;y++)for(let x=145;x<435;x++){const i=(y*640+x)*4,r=p[i],g=p[i+1],blue=p[i+2];if(g>r*1.045&&g>blue*.96&&p[i+3]>30){const light=(r+g+blue)/3/175;const tone=state.socks==='pink'?[225,147,177]:state.socks==='lavender'?[182,157,215]:[224,177,126];p[i]=Math.min(255,tone[0]*light);p[i+1]=Math.min(255,tone[1]*light);p[i+2]=Math.min(255,tone[2]*light);}else p[i+3]=0;}
 // Outside the sock range, leave the original feet untouched.
 for(let y=0;y<1000;y++)for(let x=0;x<640;x++)if(y<720||y>=865||x<145||x>=435)p[(y*640+x)*4+3]=0;sc.putImageData(pixels,0,0);c.drawImage(segment,0,0);
}
function bracelet(c,value){if(value==='none')return;c.save();c.translate(363,540);c.rotate(.63);const colors=value==='pearls'?['#fff8e4']:value==='stars'?['#f4d282','#ffeeb3']:value==='rainbow'?['#b998df','#8fd0ce','#f0bd88','#eea8bd','#e9d888']:['#e7a9c3','#b4d9a3','#ffe4a8','#b9a4df','#96c9ce'];for(let i=0;i<11;i++){const a=i*Math.PI*2/11,x=Math.cos(a)*18,y=Math.sin(a)*7;const grad=c.createRadialGradient(x-1.6,y-2,1,x,y,4.4);grad.addColorStop(0,'#fffbea');grad.addColorStop(.35,colors[i%colors.length]);grad.addColorStop(1,colors[i%colors.length]);c.fillStyle=grad;c.strokeStyle='#aa8d7955';c.lineWidth=.6;c.beginPath();c.arc(x,y,4.4,0,Math.PI*2);c.fill();c.stroke();}if(value==='flowers'){c.translate(0,8);for(let i=0;i<5;i++){const a=i*1.256;c.fillStyle='#f3b4c8';c.beginPath();c.ellipse(Math.sin(a)*4,Math.cos(a)*4,3,4,-a,0,Math.PI*2);c.fill();}c.fillStyle='#fff0ad';c.beginPath();c.arc(0,0,2.6,0,Math.PI*2);c.fill();}c.restore();}
function renderDoll(){if(!ready)return;ctx.clearRect(0,0,640,1000);const replaceFeet=state.shoes!==0||state.socks!=='mint';if(replaceFeet){ctx.save();ctx.beginPath();ctx.rect(0,760,640,240);ctx.clip();feet(ctx);ctx.restore();}ctx.save();if(replaceFeet){ctx.beginPath();ctx.rect(0,0,640,760);ctx.clip();}base(ctx,state.outfit);ctx.restore();recolorHair(ctx,state.hair);bracelet(ctx,state.bracelet);
 if(state.lip!=='natural'){const tones={rose:'#c7758c',peach:'#c78674',berry:'#a75e84'};ctx.save();ctx.globalAlpha=.5;ctx.strokeStyle=tones[state.lip];ctx.lineWidth=4.2;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(313,239);ctx.quadraticCurveTo(336,247,356,229);ctx.stroke();ctx.restore();}
 $('doll').setAttribute('aria-label',`Dein Charakter: ${DB.clothes.find(a=>a.kind==='outfit'&&a.value===state.outfit).name}`);
}
const thumbs=new Map();
function thumbnail(item){const key=[item.kind,item.value,item.art,item.tint].join(':');if(thumbs.has(key))return thumbs.get(key);const canvas=document.createElement('canvas');canvas.width=200;canvas.height=200;const c=canvas.getContext('2d');
 if(item.art){const [x,y,w,h]=crop[item.art],scale=Math.min(190/w,190/h);c.drawImage(images.reference,x,y,w,h,(200-w*scale)/2,(200-h*scale)/2,w*scale,h*scale);}
 else if(item.foot!==undefined){const b=feetBounds[item.foot],cut=b.h*.57;c.drawImage(images.feet,b.x,b.y+cut,b.w,b.h-cut,5,30,190,150);}
 else if(item.hair){const head=document.createElement('canvas');head.width=640;head.height=1000;const hc=head.getContext('2d');base(hc,0);recolorHair(hc,item.value,0);c.drawImage(head,95,12,450,370,2,4,196,190);}
 else return null;
 const url=canvas.toDataURL('image/png');thumbs.set(key,url);return url;}
function toast(text,description=text){$('toast').textContent=text;$('toast').setAttribute('aria-label',description);$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2100);}
function save(announce=false){try{localStorage.setItem(KEY,JSON.stringify(state));$('save').textContent='✓';$('save').setAttribute('aria-label','Auf diesem Gerät gespeichert');if(announce)toast('✓ 💚','Dein Atelier ist gespeichert.');}catch(e){$('save').textContent='!';$('save').setAttribute('aria-label','Speichern nicht möglich');if(announce)toast('☁ ❗','Speichern ist gerade nicht möglich.');}}
function stats(){const hunger=Math.round(state.hunger),thirst=Math.round(state.thirst);$('hunger').value=hunger;$('thirst').value=thirst;$('joy').value=M.joy(state);$('food-fill').style.width=hunger+'%';$('water-fill').style.width=thirst+'%';$('hunger').parentElement.setAttribute('aria-label',`Hunger: ${hunger} von 100`);$('thirst').parentElement.setAttribute('aria-label',`Durst: ${thirst} von 100`);$('care-hint').hidden=state.hunger>45&&state.thirst>45;$('care-hint').textContent=state.thirst<=45?'💧?':'🍓?';$('undo').disabled=!history.length;document.querySelectorAll('.item[data-index]').forEach(b=>{const a=DB[category][Number(b.dataset.index)];b.classList.toggle('selected',!['food','drink'].includes(a.kind)&&state[a.kind]===a.value);b.setAttribute('aria-pressed',!['food','drink'].includes(a.kind)&&state[a.kind]===a.value);});}
function unlock(){try{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();}catch(e){}}
function sound(f=660){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime;o.type='sine';o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(f*1.3,t+.12);g.gain.setValueAtTime(.04,t);g.gain.exponentialRampToValueAtTime(.001,t+.24);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+.25);}
function react(item){const words=item.kind==='food'?'Mmm, lecker!':item.kind==='drink'?'Danke!': 'Schön ausgesucht!';$('reaction').textContent=item.kind==='food'?'🍓 😋':item.kind==='drink'?'💧 💚':'✨ 💜';$('reaction').setAttribute('aria-label',words);$('avatar-zone').classList.remove('show-reaction');$('doll-wrap').classList.remove('happy');void $('reaction').offsetWidth;$('avatar-zone').classList.add('show-reaction');$('doll-wrap').classList.add('happy');clearTimeout(reactionTimer);reactionTimer=setTimeout(()=>{$('avatar-zone').classList.remove('show-reaction');$('doll-wrap').classList.remove('happy');},1900);sound(item.kind==='drink'?540:740);}
function apply(item){if(!ready)return;unlock();const next=M.apply(state,item);if(next===state)return;if(!['food','drink'].includes(item.kind)&&state[item.kind]===item.value){react(item);return;}history.push({...state});if(history.length>25)history.shift();state=next;changed++;renderDoll();stats();save();react(item);$('drag-hint').hidden=true;if(changed>0&&changed%8===0)toast('🌸 ✨ 💚','Dein ganz eigener Stil!');}
function setupGesture(el,item){el.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();unlock();el.setPointerCapture(e.pointerId);gesture={id:e.pointerId,item,x:e.clientX,y:e.clientY,moved:false};});el.addEventListener('click',e=>{if(e.detail===0)apply(item);});}
function palette(cat){category=cat;const items=$('items');items.replaceChildren();items.dataset.count=DB[cat].length;items.style.gridTemplateRows=`repeat(${DB[cat].length<=4?2:3},minmax(0,1fr))`;for(let i=0;i<DB[cat].length;i++){const item=DB[cat][i],b=document.createElement('button');b.className='item';b.dataset.index=i;b.dataset.kind=item.kind;b.dataset.value=item.value;b.setAttribute('aria-label',item.name);const url=thumbnail(item);if(url){const img=new Image();img.src=url;img.className='item-picture';img.alt='';img.draggable=false;if(item.tint)img.style.filter=item.kind==='socks'?'hue-rotate(215deg)':'hue-rotate(285deg)';b.append(img);}else{const span=document.createElement('span');span.className='emoji';span.textContent=item.emoji||'🌼';b.append(span);if(item.swatch){const dot=document.createElement('span');dot.style.cssText='position:absolute;right:12px;bottom:25px;width:18px;height:18px;border-radius:50%;border:2px solid white;background:'+item.swatch;b.append(dot);}}
 const label=document.createElement('small');label.textContent=item.name;b.append(label);setupGesture(b,item);items.append(b);}
 document.querySelectorAll('[data-category]').forEach(b=>{const active=b.dataset.category===cat;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});stats();}
function inAvatar(x,y){const r=$('avatar-zone').getBoundingClientRect();return x>=r.left-14&&x<=r.right+14&&y>=r.top&&y<=r.bottom;}
function startDrag(g,x,y){drag=g.item;$('drag-ghost').replaceChildren();const url=thumbnail(drag);if(url){const img=new Image();img.src=url;$('drag-ghost').append(img);}else $('drag-ghost').textContent=drag.emoji||'🌼';$('drag-ghost').hidden=false;moveDrag(x,y);}
function moveDrag(x,y){$('drag-ghost').style.left=x+'px';$('drag-ghost').style.top=y+'px';$('avatar-zone').classList.toggle('drag-over',inAvatar(x,y));}
function cleanup(){gesture=null;drag=null;$('drag-ghost').hidden=true;$('avatar-zone').classList.remove('drag-over');}
document.addEventListener('pointermove',e=>{if(!gesture||gesture.id!==e.pointerId)return;if(!gesture.moved&&Math.hypot(e.clientX-gesture.x,e.clientY-gesture.y)>7){gesture.moved=true;startDrag(gesture,e.clientX,e.clientY);}if(gesture.moved)moveDrag(e.clientX,e.clientY);},{passive:true});
document.addEventListener('pointerup',e=>{if(!gesture||gesture.id!==e.pointerId)return;const g=gesture,ok=!g.moved||inAvatar(e.clientX,e.clientY);cleanup();if(ok)apply(g.item);});document.addEventListener('pointercancel',cleanup);window.addEventListener('blur',cleanup);
for(const b of document.querySelectorAll('[data-category]'))b.onclick=()=>{unlock();palette(b.dataset.category);sound(420);};for(const b of document.querySelectorAll('[data-care]'))setupGesture(b,b.dataset.care==='food'?DB.food[0]:DB.food[3]);
$('doll').onclick=()=>{if(!drag)react({kind:'outfit'});};$('save').onclick=()=>save(true);$('undo').onclick=()=>{if(!history.length)return;unlock();const old=history.pop();state={...old,updatedAt:Date.now()};renderDoll();stats();save();sound(480);toast('↶ 💜','Zurück!');};
function note(){if(!music||document.hidden||!audioCtx)return;const notes=[60,64,67,72,69,67,64,62,65,69,72,74,72,69,65,62],o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime;o.type='sine';o.frequency.value=440*Math.pow(2,(notes[noteIndex++%notes.length]-69)/12);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.025,t+.05);g.gain.exponentialRampToValueAtTime(.001,t+.8);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+.82);}
$('music').onclick=()=>{unlock();music=!music;$('music').setAttribute('aria-pressed',music);$('music').setAttribute('aria-label',music?'Musik ausschalten':'Musik einschalten');clearInterval(musicTimer);if(music){note();musicTimer=setInterval(note,480);}};
let lastTick=Date.now(),saveTicks=0;setInterval(()=>{if(document.hidden||!ready){lastTick=Date.now();return;}const now=Date.now();state=M.advance(state,(now-lastTick)/1000,now);lastTick=now;stats();if(++saveTicks>=10){saveTicks=0;save();}},3000);
document.addEventListener('visibilitychange',()=>{lastTick=Date.now();if(document.hidden){cleanup();save();audioCtx?.suspend();}else if(music)audioCtx?.resume();});window.addEventListener('pagehide',()=>save());
Promise.all(['dolls','feet','reference'].map(async name=>{images[name]=await loadImage('./atelier-assets/'+name+'.webp');})).then(()=>{ready=true;renderDoll();palette('clothes');stats();save();$('loading').hidden=true;}).catch(()=>{$('loading').innerHTML='<span>Die Bilder konnten nicht laden.</span><button id="retry">↻ Noch einmal</button>';$('retry').onclick=()=>location.reload();});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
