'use strict';
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const LEVEL_NAMES = {easy:'Facile',normal:'Media',hard:'Super'};
const MODE_NAMES = {solo:'Da sola',ai:'Robot',friend:'Amico'};
const config = {game:'blocks',mode:'solo',level:'easy',friend:'Amico'};
let records={},storageWorks=true;
try { records=JSON.parse(localStorage.getItem('naya-records-v1')||'{}'); if(!records||typeof records!=='object'||Array.isArray(records))records={}; } catch {storageWorks=false;}
if(!storageWorks)$('#save-status').textContent='I record restano qui finché il gioco è aperto.';
const recordKey=()=>`${config.game}-${config.mode}-${config.level}`;
let paused=false,finished=false,playing=false,session=0,activeGame=null,lastFrame=0,elapsed=0,celebrated=false,initialRecord=0;
let timers=new Set();
function later(fn,ms){const token=session;const id=setTimeout(()=>{timers.delete(id);if(token===session&&!finished)fn();},ms);timers.add(id);return id;}
function clearTimers(){for(const id of timers)clearTimeout(id);timers.clear();}
function saveRecord(score){const key=recordKey();if(score>(Number(records[key])||0)){records[key]=score;try{localStorage.setItem('naya-records-v1',JSON.stringify(records));}catch{storageWorks=false;$('#save-status').textContent='I record restano qui finché il gioco è aperto.';}return true;}return false;}
function liveRecord(score){if(score>0&&score>(Number(records[recordKey()])||0)&&!celebrated){celebrated=true;celebrate('🏆 Nuovo record, Naya!',true);}saveRecord(score);}
function screen(id){for(const el of $$('.screen'))el.hidden=el.id!==id;window.scrollTo(0,0);}
function shutdown(){session++;clearTimers();playing=false;paused=false;finished=true;activeGame=null;for(const d of $$('dialog'))if(d.open)d.close();audio.setPlaying(false);stopHolds();}
function home(){shutdown();screen('home');}
function setup(game){shutdown();config.game=game;screen('setup');$('#setup-title').textContent=game==='blocks'?'Blocchi':'Memory';$('#setup-icon').textContent=game==='blocks'?'▦':'🍓';$('#setup-description').textContent=game==='blocks'?'Sposta e gira i blocchi. Completa le righe per farle sparire.':'Gira due carte. Se sono uguali, hai trovato una coppia!';updateSetup();}
function updateSetup(){for(const b of $$('#mode-choices button')){const selected=b.dataset.mode===config.mode;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected);}for(const b of $$('#level-choices button')){const selected=b.dataset.level===config.level;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected);}$('#friend-label').hidden=config.mode!=='friend';const texts={blocks:{solo:'Gioca con calma e prova a superare il tuo record.',ai:'Due campi, 2 minuti. Vince chi fa più punti! Il robot gioca da solo.',friend:'Due campi sullo stesso iPad, 2 minuti. Ognuno ha i suoi pulsanti.'},memory:{solo:'Trova le coppie. Più coppie di fila trovi, più punti fai!',ai:'Un turno a testa. Chi trova una coppia può giocare ancora. Il robot ricorda alcune carte.',friend:'Passatevi l’iPad a ogni turno. Chi trova una coppia può giocare ancora.'}};$('#mode-help').textContent=texts[config.game][config.mode];}
for(const b of $$('[data-game]'))b.onclick=()=>setup(b.dataset.game);
for(const b of $$('[data-home]'))b.onclick=home;
$('.brand').onclick=e=>{e.preventDefault();home();};
for(const b of $$('[data-mode]'))b.onclick=()=>{config.mode=b.dataset.mode;updateSetup();};
for(const b of $$('[data-level]'))b.onclick=()=>{config.level=b.dataset.level;updateSetup();};
$('#start').onclick=start;
$('#leave-game').onclick=()=>{pauseGame();};
$('#pause').onclick=pauseGame;
$('#resume').onclick=resume;
$('#pause-home').onclick=home;
$('#again').onclick=start;
$('#result-home').onclick=home;
for(const b of $$('[data-close]'))b.onclick=()=>$('#'+b.dataset.close).close();
$('#records-button').onclick=()=>{if(playing&&!finished)pauseGame();const entries=Object.entries(records).filter(([k,v])=>/^(blocks|memory)-(solo|ai|friend)-(easy|normal|hard)$/.test(k)&&Number.isFinite(v)&&v>=0);$('#records-list').replaceChildren();for(const [key,value]of entries){const [game,mode,level]=key.split('-');const row=document.createElement('div');row.className='record-row';const label=document.createElement('span');label.textContent=`${game==='blocks'?'▦ Blocchi':'🍓 Memory'} · ${MODE_NAMES[mode]} · ${LEVEL_NAMES[level]}`;const score=document.createElement('strong');score.textContent=`${value} pt`;row.append(label,score);$('#records-list').append(row);}if(!entries.length)$('#records-list').textContent='Il primo record ti aspetta!';$('#records-dialog').showModal();};
$('#pause-dialog').addEventListener('cancel',e=>{e.preventDefault();resume();});
$('#result-dialog').addEventListener('cancel',e=>{e.preventDefault();home();});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing&&!finished)pauseGame();});
function pauseGame(){if(!playing||finished||paused)return;paused=true;audio.setPlaying(false);stopHolds();$('#pause-dialog').showModal();}
function resume(){if(!playing||finished)return;$('#pause-dialog').close();paused=false;lastFrame=performance.now();audio.unlock();audio.setPlaying(true);if(activeGame==='memory'){memory.render();if(config.mode==='ai'&&memory.turn===1&&!memory.locked)memory.aiTurn();}}
function start(){shutdown();config.friend=$('#friend-name').value.trim()||'Amico';finished=false;playing=true;paused=false;elapsed=0;celebrated=false;initialRecord=Number(records[recordKey()])||0;screen('play');$('#play-title').textContent=config.game==='blocks'?'Blocchi':'Memory';$('#blocks-area').hidden=config.game!=='blocks';$('#memory-area').hidden=config.game!=='memory';audio.unlock();audio.setPlaying(true);activeGame=config.game;if(activeGame==='blocks')startBlocks();else memory.start();lastFrame=performance.now();}
function endGame(scores,message){if(finished)return;const previous=initialRecord;liveRecord(scores[0]);finished=true;playing=false;clearTimers();stopHolds();audio.setPlaying(false);const names=['Naya',config.mode==='ai'?'Robot':config.friend];const winner=scores.length>1?(scores[0]===scores[1]?-1:scores[0]>scores[1]?0:1):0;$('#result-symbol').textContent=winner===0?'🏆':winner===-1?'🤝':'🌟';$('#result-title').textContent=scores.length===1?'Bravissima, Naya!':winner===-1?'Avete pareggiato!':winner===0?'Hai vinto, Naya!':`Vince ${names[1]}!`;$('#result-message').textContent=message+(scores[0]>previous?' Hai fatto un nuovo record!':'');$('#result-scores').replaceChildren();scores.forEach((score,i)=>{const row=document.createElement('div');row.className='result-row';const label=document.createElement('span');label.textContent=names[i];const value=document.createElement('strong');value.textContent=`${score} punti`;row.append(label,value);$('#result-scores').append(row);});$('#result-dialog').showModal();confetti(winner===0?110:45);audio.fanfare();}

// Music and feedback are synthesized here: no downloads or external audio.
const audio={ctx:null,music:false,sfx:true,playing:false,beat:0,clock:null,
 unlock(){try{if(!this.ctx)this.ctx=new(window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});}catch{}},
 tone(freq,duration=.12,volume=.06,type='sine',delay=0){if(!this.ctx||this.ctx.state!=='running')return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.ctx.destination);o.start(t);o.stop(t+duration+.01);},
 effect(kind){if(!this.sfx)return;this.unlock();if(kind==='match'){this.tone(660,.15);this.tone(880,.2,.06,'sine',.1);}else if(kind==='miss')this.tone(220,.12,.025);else if(kind==='line'){[523,659,784,1047].forEach((n,i)=>this.tone(n,.2,.06,'triangle',i*.07));}else if(kind==='rotate')this.tone(420,.06,.025);else this.tone(310,.06,.025);},
 fanfare(){if(!this.sfx)return;this.unlock();[523,659,784,1047,784,1047].forEach((n,i)=>this.tone(n,.32,.065,'triangle',i*.13));},
 setPlaying(value){this.playing=value;this.sync();},
 sync(){if(this.clock){clearInterval(this.clock);this.clock=null;}if(!this.music||!this.playing)return;const tune=[60,64,67,64,69,67,64,62,60,64,67,72,69,67,64,62];this.clock=setInterval(()=>{if(!this.ctx||this.ctx.state!=='running')return;const note=tune[this.beat%tune.length];this.tone(440*2**((note-69)/12),.32,.024,'triangle');if(this.beat%4===0)this.tone(130.81,.65,.028);this.beat++;},350);}
};
try{audio.music=localStorage.getItem('naya-music')!=='false';audio.sfx=localStorage.getItem('naya-sound')!=='false';}catch{}
function audioButtons(){$('#music').setAttribute('aria-pressed',audio.music);$('#music').textContent=audio.music?'♫ Musica sì':'♫ Musica no';$('#sound').setAttribute('aria-pressed',audio.sfx);$('#sound').textContent=audio.sfx?'♪ Suoni sì':'♪ Suoni no';}
$('#music').onclick=()=>{audio.unlock();audio.music=!audio.music;try{localStorage.setItem('naya-music',audio.music);}catch{}audio.sync();audioButtons();};
$('#sound').onclick=()=>{audio.unlock();audio.sfx=!audio.sfx;try{localStorage.setItem('naya-sound',audio.sfx);}catch{}audioButtons();};audioButtons();
let milestoneTimer=null,particles=[],particleFrame=0;
function celebrate(text,big=false){$('#milestone').textContent=text;$('#milestone').classList.add('show');clearTimeout(milestoneTimer);milestoneTimer=setTimeout(()=>$('#milestone').classList.remove('show'),2600);confetti(big?95:45);audio.fanfare();}
function confetti(count){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const canvas=$('#confetti'),ctx=canvas.getContext('2d');canvas.width=innerWidth;canvas.height=innerHeight;const colors=['#ff82bc','#ffe38a','#75f1c6','#ab91ff'];for(let i=0;i<count;i++)particles.push({x:innerWidth/2,y:innerHeight*.32,vx:(Math.random()-.5)*12,vy:-Math.random()*10-2,life:100+Math.random()*30,color:colors[i%4],angle:Math.random()*6});if(particleFrame)return;function tick(){ctx.clearRect(0,0,canvas.width,canvas.height);particles=particles.filter(p=>p.life>0);for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.18;p.life--;p.angle+=.08;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);ctx.fillStyle=p.color;ctx.globalAlpha=Math.min(1,p.life/25);ctx.fillRect(-4,-3,8,6);ctx.restore();}if(particles.length)particleFrame=requestAnimationFrame(tick);else{particleFrame=0;ctx.clearRect(0,0,canvas.width,canvas.height);}}particleFrame=requestAnimationFrame(tick);}

// Falling blocks: shared seven-piece bag, independent boards and real placement AI.
const W=10,H=16,COLORS=['','#75f1c6','#ab91ff','#ff82bc','#ffe38a','#70b8ff','#ff9d72','#aeea80'];
const SHAPES=[[[1,1,1,1]],[[2,0,0],[2,2,2]],[[0,0,3],[3,3,3]],[[4,4],[4,4]],[[0,5,5],[5,5,0]],[[0,6,0],[6,6,6]],[[7,7,0],[0,7,7]]];
let sequence=[],boards=[],blockMilestone=0;
const clone=s=>s.map(r=>r.slice());
function shuffled(values){const a=values.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function pieceAt(i){while(sequence.length<=i)sequence.push(...shuffled([0,1,2,3,4,5,6]));return clone(SHAPES[sequence[i]]);}
function rotated(shape){return shape[0].map((_,x)=>shape.map(row=>row[x]).reverse());}
function collides(grid,shape,x,y){return shape.some((row,j)=>row.some((v,i)=>v&&(x+i<0||x+i>=W||y+j>=H||(y+j>=0&&grid[y+j][x+i]))));}
function merge(grid,shape,x,y){let overflow=false;shape.forEach((row,j)=>row.forEach((v,i)=>{if(v){if(y+j<0)overflow=true;else if(y+j<H&&x+i>=0&&x+i<W)grid[y+j][x+i]=v;}}));return overflow;}
function clearRows(grid){const remaining=grid.filter(row=>!row.every(Boolean));const count=H-remaining.length;while(remaining.length<H)remaining.unshift(Array(W).fill(0));return {grid:remaining,count};}
class Board{
 constructor(index,cpu){this.index=index;this.cpu=cpu;this.grid=Array.from({length:H},()=>Array(W).fill(0));this.score=0;this.lines=0;this.combo=0;this.cursor=0;this.dead=false;this.fall=0;this.aiTime=0;this.shape=null;this.flash=0;this.spawn();this.canvas=$(`#board-${index}`);this.ctx=this.canvas.getContext('2d');}
 spawn(){this.shape=pieceAt(this.cursor++);this.x=Math.floor((W-this.shape[0].length)/2);this.y=0;if(collides(this.grid,this.shape,this.x,this.y))this.dead=true;this.aiPlan=null;}
 move(dx,dy){if(this.dead)return false;if(!collides(this.grid,this.shape,this.x+dx,this.y+dy)){this.x+=dx;this.y+=dy;return true;}return false;}
 rotate(){if(this.dead)return;const shape=rotated(this.shape);for(const kick of [0,-1,1,-2,2])if(!collides(this.grid,shape,this.x+kick,this.y)){this.shape=shape;this.x+=kick;if(!this.cpu)audio.effect('rotate');return;}}
 lock(){if(this.dead)return;if(merge(this.grid,this.shape,this.x,this.y)){this.dead=true;return;}const result=clearRows(this.grid);this.grid=result.grid;if(result.count){this.combo++;const gain=[0,100,300,500,800][result.count]*Math.min(4,this.combo);this.score+=gain;this.lines+=result.count;this.flash=.22;if(!this.cpu){audio.effect('line');if(this.combo>=2)celebrate(`🔥 ${this.combo} righe consecutive!`);else if(result.count>=2)celebrate(`✨ ${result.count} righe insieme!`);}}else this.combo=0;this.spawn();this.fall=0;}
 drop(){if(this.dead)return;while(this.move(0,1)){}this.lock();if(!this.cpu)audio.effect('drop');}
 tick(dt){if(this.dead)return;this.flash=Math.max(0,this.flash-dt);if(this.cpu){this.aiTime+=dt;const delay={easy:2.2,normal:1.35,hard:.75}[config.level];if(this.aiTime>=delay){this.aiTime=0;this.aiPlace();}}else{this.fall+=dt;const speed={easy:1.15,normal:.78,hard:.45}[config.level]/(1+Math.min(.85,this.lines*.018));if(this.fall>=speed){this.fall=0;if(!this.move(0,1))this.lock();}}}
 aiPlace(){let best=null;let shape=clone(this.shape);for(let r=0;r<4;r++){for(let x=0;x<=W-shape[0].length;x++){if(collides(this.grid,shape,x,0))continue;let y=0;while(!collides(this.grid,shape,x,y+1))y++;const test=clone(this.grid);merge(test,shape,x,y);const result=clearRows(test);let holes=0,height=0,bump=0,prev=0;for(let col=0;col<W;col++){let first=result.grid.findIndex(row=>row[col]);if(first<0)first=H;let h=H-first;height+=h;if(col)bump+=Math.abs(h-prev);prev=h;for(let row=first+1;row<H;row++)if(!result.grid[row][col])holes++;}const rank=result.count*9-height*.48-holes*5.5-bump*.45+(config.level==='easy'?Math.random()*3:Math.random()*.3);if(!best||rank>best.rank)best={shape:clone(shape),x,y,rank};}shape=rotated(shape);}if(best){this.shape=best.shape;this.x=best.x;this.y=best.y;this.lock();}else this.dead=true;}
 draw(){const ctx=this.ctx,cell=26;ctx.clearRect(0,0,260,416);ctx.fillStyle='#100e27';ctx.fillRect(0,0,260,416);ctx.strokeStyle='#ffffff08';ctx.lineWidth=1;for(let x=1;x<W;x++){ctx.beginPath();ctx.moveTo(x*cell,0);ctx.lineTo(x*cell,H*cell);ctx.stroke();}for(let y=1;y<H;y++){ctx.beginPath();ctx.moveTo(0,y*cell);ctx.lineTo(W*cell,y*cell);ctx.stroke();}this.grid.forEach((row,y)=>row.forEach((v,x)=>{if(v)drawCell(ctx,x,y,v,cell);}));if(!this.dead){let ghost=this.y;while(!collides(this.grid,this.shape,this.x,ghost+1))ghost++;this.shape.forEach((row,j)=>row.forEach((v,i)=>{if(v){ctx.strokeStyle=COLORS[v]+'66';ctx.lineWidth=2;ctx.strokeRect((this.x+i)*cell+3,(ghost+j)*cell+3,cell-6,cell-6);drawCell(ctx,this.x+i,this.y+j,v,cell);}}));}if(this.flash>0){ctx.fillStyle='#75f1c622';ctx.fillRect(0,0,260,416);}if(this.dead){ctx.fillStyle='#100e27bb';ctx.fillRect(0,0,260,416);ctx.fillStyle='#ffe38a';ctx.font='bold 20px system-ui';ctx.textAlign='center';ctx.fillText('Campo pieno',130,208);}const next=$(`#next-${this.index}`).getContext('2d');next.clearRect(0,0,108,68);const nextShape=pieceAt(this.cursor);nextShape.forEach((row,y)=>row.forEach((v,x)=>{if(v)drawCell(next,x,y,v,17);}));$(`#score-${this.index}`).textContent=this.score;$(`#lines-${this.index}`).textContent=`${this.lines} righe`;}
}
function drawCell(ctx,x,y,v,cell){ctx.fillStyle=COLORS[v];ctx.fillRect(x*cell+2,y*cell+2,cell-4,cell-4);ctx.fillStyle='#ffffff45';ctx.fillRect(x*cell+4,y*cell+4,cell-8,3);ctx.fillStyle='#00000017';ctx.fillRect(x*cell+4,(y+1)*cell-6,cell-8,3);}
function startBlocks(){sequence=[];boards=[];blockMilestone=0;const count=config.mode==='solo'?1:2;$('#game-hint').textContent=count===1?'◀ ▶ sposta · ↻ gira · ▼ scendi · Giù subito lascia cadere': 'Due campi, stessi blocchi. Vince chi fa più punti in 2 minuti.';$('#blocks-area').innerHTML='<div class="boards"></div>';for(let i=0;i<count;i++){const cpu=i===1&&config.mode==='ai',panel=document.createElement('div');panel.className='board-panel'+(cpu?' cpu':'');panel.innerHTML=`<div class="board-heading"><h2></h2><strong id="score-${i}">0</strong></div><div class="board-wrap"><canvas class="block-board" id="board-${i}" width="260" height="416" role="img" aria-label="Campo di blocchi"></canvas></div><div class="board-meta"><span id="lines-${i}">0 righe</span><span class="next-piece">Dopo <canvas id="next-${i}" width="108" height="68" aria-label="Prossimo blocco"></canvas></span></div>`;panel.querySelector('h2').textContent=i===0?'Naya':cpu?'🤖 Robot':config.friend;if(!cpu){const controls=document.createElement('div');controls.className='controls';controls.innerHTML=`<button class="control" data-action="left" aria-label="Sposta a sinistra">◀</button><button class="control rotate" data-action="rotate" aria-label="Gira il blocco">↻</button><button class="control" data-action="right" aria-label="Sposta a destra">▶</button><button class="control down" data-action="down" aria-label="Scendi di un passo">▼</button><button class="control drop" data-action="drop">Giù subito ⤓</button>`;panel.append(controls);for(const b of controls.querySelectorAll('button'))bindControl(b,i);}else{const label=document.createElement('div');label.className='cpu-label';label.textContent='Il robot pensa e gioca…';panel.append(label);}$('#blocks-area .boards').append(panel);boards.push(new Board(i,cpu));}renderBlockStats();for(const b of boards)b.draw();}
function renderBlockStats(){const best=Number(records[recordKey()])||0;$('#game-stats').innerHTML=`<div class="stat"><small>RECORD</small><strong>${best}</strong></div><div class="stat"><small>${config.mode==='solo'?'TEMPO':'ANCORA'}</small><strong>${formatTime(config.mode==='solo'?elapsed:Math.max(0,120-elapsed))}</strong></div><div class="stat"><small>LIVELLO</small><strong>${LEVEL_NAMES[config.level]}</strong></div>`;}
function formatTime(time){const n=Math.max(0,Math.ceil(time));return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;}
let holds=new Map();
function stopHolds(){for(const {delay,repeat}of holds.values()){clearTimeout(delay);clearInterval(repeat);}holds.clear();}
function action(i,name){if(!playing||paused||finished||activeGame!=='blocks'||boards[i]?.cpu)return;const b=boards[i];if(!b||b.dead)return;if(name==='left')b.move(-1,0);if(name==='right')b.move(1,0);if(name==='rotate')b.rotate();if(name==='down'){if(!b.move(0,1))b.lock();}if(name==='drop')b.drop();b.draw();}
function bindControl(button,i){const name=button.dataset.action;button.addEventListener('pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);action(i,name);if(['left','right','down'].includes(name)){const hold={delay:null,repeat:null};hold.delay=setTimeout(()=>{hold.repeat=setInterval(()=>action(i,name),100);},280);holds.set(button,hold);}});const stop=()=>{const h=holds.get(button);if(h){clearTimeout(h.delay);clearInterval(h.repeat);holds.delete(button);}};button.addEventListener('pointerup',stop);button.addEventListener('pointercancel',stop);button.addEventListener('lostpointercapture',stop);button.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();action(i,name);}});}
document.addEventListener('keydown',e=>{if(!playing||paused||finished||activeGame!=='blocks'||e.target instanceof HTMLInputElement)return;const map={ArrowLeft:[0,'left'],ArrowRight:[0,'right'],ArrowUp:[0,'rotate'],ArrowDown:[0,'down'],' ':[0,'drop'],a:[1,'left'],d:[1,'right'],w:[1,'rotate'],s:[1,'down'],q:[1,'drop']};const command=map[e.key];if(command){e.preventDefault();action(...command);}if(e.key==='Escape'){e.preventDefault();pauseGame();}});

// Memory: per-turn scoring and imperfect observation-based AI (never reads hidden cards).
const SYMBOLS=['🍓','🐱','🌈','🦋','🐳','🍒','🌻','🚀','🐢','🍉','🦄','🐝'];
const memory={cards:[],open:[],matched:new Set(),known:new Map(),turn:0,scores:[0,0],combos:[0,0],locked:false,pairs:0,moves:0,aiPending:false,
 start(){const n={easy:6,normal:8,hard:12}[config.level];this.cards=shuffled([...SYMBOLS.slice(0,n),...SYMBOLS.slice(0,n)]);this.open=[];this.matched=new Set();this.known=new Map();this.turn=0;this.scores=[0,0];this.combos=[0,0];this.locked=false;this.pairs=0;this.moves=0;this.aiPending=false;$('#game-hint').textContent=config.mode==='solo'?'Trova due carte uguali. Le coppie di fila valgono di più!':'Chi trova una coppia gioca ancora. Vince chi fa più punti.';const grid=$('#memory-grid');grid.style.gridTemplateColumns=`repeat(${n===12?6:4},1fr)`;grid.replaceChildren();this.cards.forEach((_,i)=>{const card=document.createElement('button');card.className='memory-tile';card.setAttribute('aria-label',`Carta ${i+1}, coperta`);card.innerHTML='<span class="back" aria-hidden="true">★</span><span class="symbol" aria-hidden="true"></span>';card.onclick=()=>this.flip(i,false);grid.append(card);});this.render();},
 observe(i){this.known.set(i,this.cards[i]);const capacity={easy:4,normal:9,hard:24}[config.level];while(this.known.size>capacity)this.known.delete(this.known.keys().next().value);},
 flip(i,cpu){if(!playing||finished||paused||this.locked||this.matched.has(i)||this.open.includes(i))return;if(config.mode==='ai'&&this.turn===1&&!cpu)return;if(cpu&&this.turn!==1)return;this.open.push(i);this.observe(i);audio.effect('flip');this.render();if(this.open.length===2){this.locked=true;this.moves++;this.resolve();}},
 resolve(){const token=session;const done=()=>{if(token!==session||finished)return;if(paused){later(done,150);return;}const [a,b]=this.open;if(this.cards[a]===this.cards[b]){this.matched.add(a);this.matched.add(b);this.known.delete(a);this.known.delete(b);this.pairs++;this.combos[this.turn]++;const points=100+25*Math.min(4,this.combos[this.turn]-1);this.scores[this.turn]+=points;audio.effect('match');if(this.turn===0){liveRecord(this.scores[0]);if(this.combos[0]>=2)celebrate(`🔥 ${this.combos[0]} coppie di fila!`);}this.open=[];this.locked=false;this.render();if(this.matched.size===this.cards.length){endGame(config.mode==='solo'?[this.scores[0]]:this.scores,`Tutte le coppie trovate in ${this.moves} tentativi!`);return;}}else{this.combos[this.turn]=0;this.open=[];audio.effect('miss');if(config.mode!=='solo')this.turn=1-this.turn;this.locked=false;this.render();}if(config.mode==='ai'&&this.turn===1)this.aiTurn();};later(done,this.cards[this.open[0]]===this.cards[this.open[1]]?650:1100);},
 aiTurn(){if(this.aiPending||finished||this.turn!==1)return;this.aiPending=true;const run=()=>{if(finished)return;if(paused){later(run,150);return;}if(this.turn!==1||this.locked){this.aiPending=false;return;}const available=this.cards.map((_,i)=>i).filter(i=>!this.matched.has(i));const remembered=[...this.known.entries()].filter(([i])=>available.includes(i));const accuracy={easy:.5,normal:.8,hard:1}[config.level];let pair=null;if(Math.random()<accuracy){for(let a=0;a<remembered.length;a++)for(let b=a+1;b<remembered.length;b++)if(remembered[a][1]===remembered[b][1])pair=[remembered[a][0],remembered[b][0]];}const first=pair?pair[0]:available[Math.floor(Math.random()*available.length)];this.flip(first,true);const secondStep=()=>{if(paused){later(secondStep,150);return;}if(finished||this.turn!==1)return;const candidates=available.filter(i=>i!==first);let second=pair?pair[1]:null;if(second===null&&Math.random()<accuracy){const match=[...this.known.entries()].find(([i,s])=>i!==first&&candidates.includes(i)&&s===this.known.get(first));if(match)second=match[0];}if(second===null)second=candidates[Math.floor(Math.random()*candidates.length)];this.aiPending=false;this.flip(second,true);};later(secondStep,700);};later(run,850);},
 render(){const tiles=$$('#memory-grid .memory-tile');tiles.forEach((card,i)=>{const shown=this.open.includes(i)||this.matched.has(i);card.classList.toggle('open',this.open.includes(i));card.classList.toggle('matched',this.matched.has(i));card.querySelector('.symbol').textContent=shown?this.cards[i]:'';card.setAttribute('aria-label',`Carta ${i+1}, ${this.matched.has(i)?'coppia trovata, ':shown?'':'coperta'}${shown?this.cards[i]:''}`);card.disabled=this.matched.has(i)||this.locked||paused||(config.mode==='ai'&&this.turn===1);});const name=this.turn===0?'Naya':config.mode==='ai'?'Robot':config.friend;$('#turn-banner').replaceChildren();const turn=document.createElement('span');turn.textContent=config.mode==='solo'?'⭐ Cerca una coppia':`${this.turn===0?'⭐':config.mode==='ai'?'🤖':'🙌'} Tocca a ${name}`;const streak=document.createElement('span');streak.className='streak';streak.textContent=`${this.pairs}/${this.cards.length/2} coppie`;$('#turn-banner').append(turn,streak);$('#game-stats').replaceChildren();const items=[['NAYA',this.scores[0]],...(config.mode==='solo'?[]:[[config.mode==='ai'?'ROBOT':config.friend,this.scores[1]]]),['RECORD',Number(records[recordKey()])||0]];for(const [label,value]of items){const stat=document.createElement('div');stat.className='stat';const small=document.createElement('small');small.textContent=label;const strong=document.createElement('strong');strong.textContent=value;stat.append(small,strong);$('#game-stats').append(stat);}}
};
let statTick=0;
function frame(now){const dt=Math.min(.1,(now-(lastFrame||now))/1000);lastFrame=now;if(playing&&!paused&&!finished){elapsed+=dt;if(activeGame==='blocks'){for(const board of boards){board.tick(dt);board.draw();}liveRecord(boards[0].score);const step=Math.floor(boards[0].score/500);if(step>blockMilestone){blockMilestone=step;celebrate(`🌟 ${step*500} punti!`);}statTick+=dt;if(statTick>.25){statTick=0;renderBlockStats();}if(config.mode==='solo'&&boards[0].dead)endGame([boards[0].score],`Hai completato ${boards[0].lines} righe. Pronta a riprovare?`);else if(config.mode!=='solo'&&(elapsed>=120||boards.every(b=>b.dead)))endGame(boards.map(b=>b.score),'Bella sfida! Ogni partita è una nuova avventura.');}}requestAnimationFrame(frame);}requestAnimationFrame(frame);
function connectivity(){$('#offline-status').textContent=navigator.onLine?'':'Pronta anche senza internet';}addEventListener('online',connectivity);addEventListener('offline',connectivity);connectivity();
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
